-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
FROM (
    SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
    FROM REST_INFO
    WHERE ADDRESS LIKE '서울%'
    ) AS I
INNER JOIN REST_REVIEW AS R
ON I.REST_ID = R.REST_ID
GROUP BY I.REST_ID
ORDER BY SCORE DESC, I.FAVORITES DESC;